### PR TITLE
Use the last container id

### PR DESCRIPTION
**Pull request by gdw2**
Adjust the regex to use the last container id in a scenario where there are nested docker containers (e.g. docker in docker).

For example, in this simplified example, `id1` is the parent container and `id2` is the child container.  We want the child container, `id2`:

 '../containers/<id1>/.../containers/<id2>/...'

### CODE REVIEW

**Comment by gdw2** [comment]
I tested this at the repl and then on GHA, where I discovered the issue.  I didn't write an automated test.

**Review by kanaka — APPROVED** [review]

**Review by kanaka — CHANGES_REQUESTED** [review]
I just recalled the reason for the original regex is because in podman the ID is after `overlay-containers/.../`. So I think the current change will break podman.

**Comment by gdw2** [comment]
I changed `.*/containers...` to `.*containers` so it should match for both podman and docker.

**Comment by kanaka** [comment]
Something failed. It would probably be useful to have a always() step in the workflow that dumped the compose logs for the conlink container so that we can have better insight into what's going on when things break (and make sure there are no weird things happening even when it works).

**Review by kanaka — APPROVED** [review]
Looks good.

**Pull request merged**
