### PR TITLE
Host docs with GitHub Pages and docsify

### PR DESCRIPTION
**Pull request by jonsmock**
The conlink README is fantastic.  This PR separates its content into separate pages and hosts the docs with GitHub Pages and docsify to make them more navigable and easier to consume.

I've configured GitHub Pages to point to this branch temporarily, so you can see it rendered at https://lonocloud.github.io/conlink/#/ .  The landing page pulls from the README on the master branch, so use the normal GitHub markdown rendered version to see what the updated README will feel like: 
 https://github.com/LonoCloud/conlink/tree/docsify?tab=readme-ov-file#conlink

I'm happy to iterate on this more to make sure it fits your vision and how you want the project to present itself.  The new example in the README/landing page especially could use your eyes to make sure it's on point with how you want the first experience to be.

Future:  I think there is perhaps room for an "Adding conlink to your project" guide, but there is enough in the examples and usage notes that it is actually covered between the two.

### CODE REVIEW

**Review by kanaka — APPROVED** [review]
That looks great! I haven't done in depth review, just looking at the overall changes. But we can make tweaks and fix typos, etc later so I say it's good to go.

**Comment by jonsmock** [comment]
Alternatively, if we don't want a big, not-regularly-run example in the main README, we could simply link to the test1 example and say something like "adding to your project is easy! 1) .. 2) ... 3) ..." where bullets 1-3 are the steps currently embedded in the README yaml example.

**Comment by jonsmock** [comment]
xpost :-) ok, rebased and merged, but happy to keep iterating even after this week.

**Comment by kanaka** [comment]
> Alternatively, if we don't want a big, not-regularly-run example in the main README, we could simply link to the test1 example and say something like "adding to your project is easy! 1) .. 2) ... 3) ..." where bullets 1-3 are the steps currently embedded in the README yaml example.

I like having that on the front page. It's what I would want to see if I was discovering this for the first time (and often feel is missing from projects like this).

**Pull request merged**
